#KNN

In [ ]:
import pandas as pd
import seaborn as sns
#Scaling is requred before train test split in both pipeline and KNN

In [ ]:
data=pd.read_csv("heart.csv")

In [ ]:
X=data.drop(columns=["target"])
y=data["target"]

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
# For Regression
#from sklearn.neighbors import KNeighborsRegressor

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_scaled,y_train)

KNeighborsClassifier()

In [ ]:
y_pred= knn.predict(X_test_scaled)

In [ ]:
from sklearn.metrics import precision_score,recall_score,f1_score,accuracy_score
print("Accuracy : ",accuracy_score(y_test,y_pred)*100)
print("Precision : ",precision_score(y_test,y_pred)*100)
print("Recall : ",recall_score(y_test,y_pred)*100)
print("F1 Score : ",f1_score(y_test,y_pred)*100)

Accuracy :  90.1639344262295
Precision :  93.33333333333333
Recall :  87.5
F1 Score :  90.32258064516128

In [ ]:
#For k=7
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train_scaled,y_train)

KNeighborsClassifier(n_neighbors=7)

In [ ]:
y_pred= knn.predict(X_test_scaled)

In [ ]:
from sklearn.metrics import precision_score,recall_score,f1_score,accuracy_score
print("Accuracy : ",accuracy_score(y_test,y_pred)*100)
print("Precision : ",precision_score(y_test,y_pred)*100)
print("Recall : ",recall_score(y_test,y_pred)*100)
print("F1 Score : ",f1_score(y_test,y_pred)*100)

Accuracy :  91.80327868852459
Precision :  93.54838709677419
Recall :  90.625
F1 Score :  92.06349206349206

In [ ]:
#For k=9
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=9)
knn.fit(X_train_scaled,y_train)
y_pred= knn.predict(X_test_scaled)
from sklearn.metrics import precision_score,recall_score,f1_score,accuracy_score
print("Accuracy : ",accuracy_score(y_test,y_pred)*100)
print("Precision : ",precision_score(y_test,y_pred)*100)
print("Recall : ",recall_score(y_test,y_pred)*100)
print("F1 Score : ",f1_score(y_test,y_pred)*100)

Accuracy :  90.1639344262295
Precision :  93.33333333333333
Recall :  87.5
F1 Score :  90.32258064516128

In [ ]:
#Value of recall is greater at 7 than at 5 and 9
#Best recall ----->k=7

In [ ]:
#generally this is nnot the optimal way for finding  best value of k
#For that we use Cross Validation to find optimum value of k

#NAIVE BAYES

In [ ]:
import pandas as pd
heart_data=pd.read_csv("heart.csv")

In [ ]:
X=heart_data.drop(columns=["target"])
y=heart_data["target"]

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
#WE doot need scaling in naive bayes because naive bayes deals with probability not with distance

In [ ]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(X_train,y_train)

GaussianNB()

In [ ]:
y_pred=nb.predict(X_test)

In [ ]:
y_pred

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [ ]:
from sklearn.metrics import precision_score,recall_score,f1_score,accuracy_score
print("Accuracy : ",accuracy_score(y_test,y_pred)*100)
print("Precision : ",precision_score(y_test,y_pred)*100)
print("Recall : ",recall_score(y_test,y_pred)*100) #Most important
print("F1 Score : ",f1_score(y_test,y_pred)*100)

Accuracy :  86.88524590163934
Precision :  90.0
Recall :  84.375
F1 Score :  87.09677419354838

In [ ]:
#compare with logistic Regession and select the one which give best results

# Cross Validation For Hyperarameter Tuning using GridSearchCV

In [ ]:
from sklearn.model_selection import GridSearchCV
classifier=KNeighborsClassifier()
grid_params={
    "n_neighbors":[3,5,7,9]
}
gs=GridSearchCV(classifier,grid_params,cv=5,scoring ="recall")
gs.fit(X_train_scaled,y_train)
y_pred=gs.predict(X_test_scaled)

In [ ]:
from sklearn.metrics import precision_score,recall_score,f1_score,accuracy_score
print("Accuracy : ",accuracy_score(y_test,y_pred)*100)
print("Precision : ",precision_score(y_test,y_pred)*100)
print("Recall : ",recall_score(y_test,y_pred)*100)
print("F1 Score : ",f1_score(y_test,y_pred)*100)

Accuracy :  90.1639344262295
Precision :  93.33333333333333
Recall :  87.5
F1 Score :  90.32258064516128

In [ ]:
#results
res=pd.DataFrame(gs.cv_results_)
res

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_neighbors,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.009531,0.006455,0.014764,0.009058,3,{'n_neighbors': 3},0.816327,0.795918,0.854167,0.750000,0.812500,0.805782,0.033783,2
1,0.004780,0.000858,0.008691,0.000748,5,{'n_neighbors': 5},0.775510,0.836735,0.833333,0.770833,0.854167,0.814116,0.034202,1
2,0.007233,0.005874,0.015084,0.007457,7,{'n_neighbors': 7},0.755102,0.857143,0.812500,0.750000,0.833333,0.801616,0.042510,4
3,0.005679,0.002458,0.012123,0.005046,9,{'n_neighbors': 9},0.734694,0.836735,0.833333,0.770833,0.833333,0.801786,0.041644,3

In [ ]:
print(gs.best_params_)

{'n_neighbors': 5}

In [ ]:
from sklearn.model_selection import GridSearchCV
classifier=KNeighborsClassifier()
grid_params={
    "n_neighbors":[3,5,7,9]
}
gs=GridSearchCV(classifier,grid_params,cv=5)
gs.fit(X_train_scaled,y_train)
y_pred=gs.predict(X_test_scaled)
from sklearn.metrics import precision_score,recall_score,f1_score,accuracy_score
print("Accuracy : ",accuracy_score(y_test,y_pred)*100)
print("Precision : ",precision_score(y_test,y_pred)*100)
print("Recall : ",recall_score(y_test,y_pred)*100)
print("F1 Score : ",f1_score(y_test,y_pred)*100)

Accuracy :  91.80327868852459
Precision :  93.54838709677419
Recall :  90.625
F1 Score :  92.06349206349206

In [ ]:
res=pd.DataFrame(gs.cv_results_)
res

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_neighbors,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003009,0.001130,0.008014,0.000665,3,{'n_neighbors': 3},0.851852,0.814815,0.962963,0.884615,0.807692,0.864387,0.056489,2
1,0.002286,0.000071,0.008016,0.000716,5,{'n_neighbors': 5},0.777778,0.814815,0.925926,0.923077,0.846154,0.857550,0.058803,3
2,0.002588,0.000862,0.007101,0.000299,7,{'n_neighbors': 7},0.814815,0.925926,0.925926,0.846154,0.846154,0.871795,0.045655,1
3,0.004983,0.001730,0.015244,0.001929,9,{'n_neighbors': 9},0.777778,0.888889,0.925926,0.846154,0.846154,0.856980,0.049556,4

In [ ]:
#Now the best parameter when scoring =recall
print(gs.best_params_)

{'n_neighbors': 7}

#PipeLine
#Scaling is required in both pipeline and KNN before train test split

In [ ]:
from sklearn.pipeline import Pipeline
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
pipe=Pipeline([
    ("scaler",StandardScaler()),
    ("classifier",KNeighborsClassifier())
])
grid_params={
    "classifier__n_neighbors":[3,5,7,9]
}
classifiercv=GridSearchCV(pipe,grid_params,cv=5,scoring="recall")

classifiercv.fit(X_train,y_train)
y_pred=classifiercv.predict(X_test)

In [ ]:
from sklearn.metrics import precision_score,recall_score,f1_score,accuracy_score
print("Accuracy : ",accuracy_score(y_test,y_pred)*100)
print("Precision : ",precision_score(y_test,y_pred)*100)
print("Recall : ",recall_score(y_test,y_pred)*100)
print("F1 Score : ",f1_score(y_test,y_pred)*100)

Accuracy :  91.80327868852459
Precision :  93.54838709677419
Recall :  90.625
F1 Score :  92.06349206349206