<a href="https://colab.research.google.com/github/muhibrahim786/AI-ML-Learning/blob/main/Lasso_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn import linear_model
from sklearn.metrics import mean_squared_error

In [ ]:
import pandas as pd
data=pd.read_csv("/content/insurance.csv")
data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [ ]:
X=data.drop(columns=["charges"])
y=data["charges"]

In [ ]:
X=pd.get_dummies(X,columns=["region"],drop_first=True,dtype=int)
X["sex"]=X["sex"].map({"male":1,"female":0})
X["smoker"]=X['smoker'].map({"yes":1,"no":0})
X["age_smoker"]=X["age"] * X["smoker"]
X["bmi_smoker"]=X["bmi"] * X["smoker"]

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.linear_model import Lasso
lasso_model=Lasso(alpha=0.5)
lasso_model.fit(X_train,y_train)
y_pred=lasso_model.predict(X_test)
y_pred

array([11233.96054447,  7418.76290865, 33108.80834567, 10826.40695911,
       28176.94762938,  6500.19887073,  2790.00110411, 14426.67722374,
        5671.57381463, 11677.01254058, 20679.57658641,  9149.08976184,
        5694.32105901, 51898.82169528, 52085.13502821, 46624.03845659,
       11691.54712201, 43244.94486795, 10134.62857431, 27553.22604481,
        5588.00753137,  9116.18804024,  1830.67548342,  4562.18621012,
       12450.88513732, 12832.35893353, 13237.62883992,  6447.50376563,
       11789.81465509,  1826.3581541 ,  9706.56019176, 12981.092064  ,
        3236.82122087,  7019.02198342,  4126.76906367, 10090.40514193,
        3259.01913951,  9119.74592388, 26295.66385368, 37683.36440542,
        4630.10769748,  3703.51305653, 12662.73931813, 12851.97337624,
        6815.18086223, 12756.38652141,  4473.45575451,  5193.30072589,
       41607.23488698,  6344.02179702, 14316.0588184 ,  2273.16883481,
        9171.46577697,  2702.16621434, 11912.85646258, 12171.1958257 ,
        5845.2946066 , 36417.22655783, 12669.79449532, 12581.15300879,
       13958.11866281,  6702.15693269, 14387.44067015,  9818.05717933,
       12268.58745089,  5691.84907389, 20696.78185714, 12081.78328953,
        4831.3467774 ,  2809.52165642,  8654.28409202, 11645.4932526 ,
       10307.9485639 ,  8322.62476259,  9294.3581839 ,  7079.91677433,
        6593.06071356, 12589.35278592,  5965.14084916, 10484.1096467 ,
        2418.98637423, 32396.88354815,  6686.61437105, 38377.57123973,
       59853.32022728, 36859.31715237,  6401.69759834, 11952.05485651,
       10199.89974239, 12293.20240272, 15975.54490028, 26973.54323889,
       28565.56958454,  7079.60903176, 37708.4970491 ,  8581.68999888,
       27290.9835106 ,  2934.77743368, 20694.1031178 ,  8567.51254264,
        6269.47595757,  2322.08937113,  8088.09587589, 13072.03075628,
       13963.2285555 ,  2394.63798973,  9603.65661375, 20429.41806665,
        2605.1784071 , 24362.57264442,  1886.93049514,  4735.35654924,
       14341.60261226, 33753.43988087, 11940.21593621,  2610.7827356 ,
       13803.07240898, 27602.57892046,  8287.04127717,  3883.4626331 ,
        8045.44911272,  9224.30479603, 13350.66310156,  3524.02733482,
        6111.15730443,  9723.21935196,  9503.52171447, 11397.75583417,
       13240.81217883,  3386.99824867,  6006.96200561,  7774.4042834 ,
        7866.30337062, 10581.40232585,  7664.98626576, 12956.40434084,
        6838.41288441, 30802.37670561, 45778.99261732, 32387.11803822,
        7353.44458949, 12068.84444427,  4041.02381698, 12710.1502837 ,
        3576.25719961, 27029.6469611 ,  6979.11558049,  5483.24020232,
       12886.16996151,  6504.9245034 , 46437.12620971,  3959.11027249,
        2055.54523887, 35247.35415322,  8627.48772438,  7089.61880916,
       14402.47206571, 10425.21300725, 30134.4095717 , 36090.924448  ,
       14792.58033087,  3320.15254292, 14495.06335183,  3983.92729713,
        4319.48568035,  9212.71302821, 48343.64729177, 37621.15763026,
       35027.72725003,  3929.75053311, 10519.05519061,  8121.58948554,
        8571.29353543,  5958.42835022,  3073.83197831, 26019.01813084,
       21293.67188555, 14143.56522139, 11991.8852353 , 12800.97185057,
       34739.79754865,  4282.95699682, 10035.12409329,  6831.1817991 ,
        6909.4143206 ,  4331.05612053,  6132.15749267,  5190.98895422,
       10757.53428016, 11845.17033425,  4411.16051426,  3288.17186249,
        4215.80118428, 38196.85320484, 13583.02319313, 11113.23760816,
        3294.42108385, 13678.89276662,  3228.79157234, 10408.8747117 ,
        4625.63695452, 30118.65766622,  6202.40896918,  3292.00913564,
       21527.64014421, 19805.25555376, 10504.02896132,  4942.0769233 ,
        9927.37788446,  4194.67000927, 12955.68403699, 12943.73116346,
       11974.0641914 , 22456.94382763,  8432.15139858,  6419.42419671,
        6719.14653994, 14475.81816196, 13281.58268938,  7369.07153126,
        3591.29374733,  9198.68639933,  8554.96591304, 44255.7726911 ,
        3256.49402393, 29863.85987189,  2149.15729808,  2435.57858753,
       10968.62549144, 12592.04409597,  2755.40822413, 11115.59543166,
        5789.0254372 , 27791.77921137, 11384.61544345, 10121.70374181,
        5208.79804924,  7958.65128847, 47952.79430895,  2954.31782317,
       14111.97003645, 36476.78684407,  4617.89021936,  4911.95072323,
        2322.75603625,  4287.04918197,  5586.36550405,  5736.51374461,
       13954.15362162,  2162.42925286,  2599.75598657,  8846.05088027,
        4625.23812857, 13403.87715133,  3446.83049522,  4696.99802826,
       12585.78399288,  4809.28324876, 10782.49264616,  8124.50977054,
        9831.94136761, 13809.75423556, 25832.88694652, 44199.64470683,
       13147.18623954,  8466.24650656, 60682.1821169 , 11313.99310102])

In [ ]:
y_test

764      9095.06825
887      5272.17580
890     29330.98315
1293     9301.89355
259     33750.29180
           ...
109     47055.53210
575     12222.89830
535      6067.12675
543     63770.42801
846      9872.70100
Name: charges, Length: 268, dtype: float64

In [ ]:
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_test,y_pred)
mse

20918648.8898256

In [ ]:
#Cross validation (CV) is used to demonstrate or find the best value of alpha for which the mse should be smallest.

#Lasso CV

In [ ]:
from sklearn.linear_model import LassoCV
a=[0.001,0.1,1,2,5,10,20,30,40,50,100]
lasso_cv_model=LassoCV(alphas=a,cv=10,max_iter=100000,random_state=42)
lasso_cv_model.fit(X_train,y_train)
y_pred=lasso_cv_model.predict(X_test)

In [ ]:
y_pred

array([11244.90059978,  7419.09546268, 33108.56314007, 10825.70490225,
       28165.85343431,  6492.31635767,  2795.32365354, 14417.83354245,
        5686.99898738, 11674.71818244, 20657.63411334,  9146.42228702,
        5695.47634768, 51922.22671926, 52110.29374917, 46640.13982805,
       11685.29658629, 43258.62998667, 10134.76616091, 27544.19263391,
        5590.70961111,  9112.26802402,  1829.44144206,  4568.32135944,
       12451.66467979, 12838.43441863, 13233.1683341 ,  6449.57391511,
       11799.9295961 ,  1825.10892897,  9707.98336691, 12978.53929819,
        3236.118998  ,  7025.38251479,  4125.34903234, 10091.32515432,
        3262.60158493,  9119.59900771, 26284.76520845, 37686.42549368,
        4634.26679081,  3702.06925208, 12658.70586842, 12849.09340889,
        6810.6449285 , 12752.77601579,  4474.36939417,  5198.07859716,
       41615.56500411,  6338.52575124, 14310.54334662,  2272.59365192,
        9166.72907954,  2711.78458203, 11905.93655599, 12175.66877205,
        5854.00924076, 36417.51200106, 12666.41162659, 12587.07781541,
       13954.80847283,  6697.60648305, 14380.52576751,  9820.67482645,
       12275.65493491,  5695.10870672, 20674.22476684, 12079.79615638,
        4836.40731729,  2803.99222195,  8657.44743854, 11653.20457265,
       10305.23215428,  8318.98850801,  9287.37575286,  7079.8937163 ,
        6599.9528502 , 12589.61154379,  5965.23409762, 10486.27971049,
        2416.13689962, 32401.1713934 ,  6687.94338633, 38390.73954383,
       59888.16859707, 36869.69504269,  6399.63222222, 11946.36095393,
       10199.91447161, 12286.86510279, 15979.11685424, 26964.46170898,
       28565.60459074,  7087.93619342, 37711.49401127,  8578.14494763,
       27278.78947241,  2934.99610732, 20673.6406664 ,  8580.20006347,
        6271.45154337,  2324.43730701,  8080.1103348 , 13065.61409598,
       13969.64678911,  2391.5024453 ,  9600.24674745, 20408.28290811,
        2616.8411115 , 24348.9853838 ,  1884.51069457,  4726.44802009,
       14347.74054823, 33760.58687462, 11947.95996808,  2608.64308485,
       13807.42079088, 27593.64603882,  8287.20386358,  3883.67146879,
        8053.60312154,  9220.05191723, 13355.10637673,  3519.66816604,
        6115.670684  ,  9722.39034919,  9500.62494561, 11402.99385547,
       13236.17838801,  3380.0817494 ,  6007.77231983,  7770.63294723,
        7864.44305338, 10585.91309889,  7663.62846896, 12948.57780249,
        6842.53129398, 30796.57834414, 45796.51118009, 32392.71530267,
        7355.15394171, 12074.67649973,  4036.65858609, 12706.26425338,
        3576.24278353, 27017.91910951,  6978.62209161,  5484.30452256,
       12883.22011483,  6502.38805081, 46454.89172918,  3961.57267977,
        2049.4651429 , 35254.4449118 ,  8623.32581431,  7093.8878972 ,
       14405.07746785, 10424.67124089, 30128.41667851, 36099.51111487,
       14799.30447507,  3324.39245428, 14492.12490829,  3993.75668215,
        4317.85059779,  9206.65224506, 48366.23900302, 37627.24292012,
       35034.90122836,  3930.88574007, 10522.08724628,  8120.69932105,
        8571.55980392,  5958.46581551,  3076.67147492, 26005.4768586 ,
       21273.26641383, 14133.1911481 , 11959.16579394, 12802.21571006,
       34749.69063244,  4299.62419594, 10036.3625006 ,  6830.26287287,
        6920.52960296,  4331.12421569,  6139.47192568,  5192.76776103,
       10749.98775109, 11841.72937416,  4407.59308336,  3299.37837528,
        4229.2375361 , 38200.76942462, 13573.5730474 , 11109.88409218,
        3299.20337026, 13687.30886058,  3241.24971985, 10409.58280629,
        4630.38712813, 30111.49628435,  6194.45221032,  3292.99416765,
       21508.82043569, 19784.50230486, 10501.62861862,  4948.65054622,
        9918.7431128 ,  4200.31321324, 12954.11764214, 12944.56003911,
       11974.84979935, 22437.85246421,  8431.65217898,  6429.97730292,
        6720.48293923, 14475.42869846, 13281.5351948 ,  7367.59996336,
        3590.61775896,  9191.12642776,  8545.63301331, 44268.2939878 ,
        3254.38056893, 29855.61266757,  2155.15034559,  2434.43161646,
       10964.47205682, 12586.99671861,  2750.91322238, 11119.69012446,
        5792.93708229, 27781.63400864, 11388.48532431, 10114.41858292,
        5207.50013799,  7953.50040303, 47972.82393541,  2951.07581678,
       14123.74752547, 36478.13324565,  4617.35801217,  4913.26003118,
        2323.98717114,  4284.99606583,  5589.10320438,  5733.83706734,
       13946.82436214,  2167.03980149,  2601.69685493,  8841.57993154,
        4628.05065546, 13414.2430183 ,  3448.40025253,  4697.3925018 ,
       12581.12311939,  4806.31437919, 10790.60731528,  8134.8444009 ,
        9833.46706782, 13811.51736663, 25818.74112993, 44213.43076855,
       13146.57816197,  8473.37336301, 60721.8108595 , 11311.16056578])

In [ ]:
print("Best alpha : ",lasso_cv_model.alpha_)

Best alpha :  0.001

In [ ]:
y_pred=lasso_cv_model.predict(X_test)
mse=mean_squared_error(y_test,y_pred)
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
print("R2 score :",r2)
print("Mean squared error :",mse)

R2 score : 0.8652317499151699
Mean squared error : 20922599.87103596